name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 2
          repo: dev-drprasad/hoodiee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
